agent:
  type: python
  name: gdpval-python-agent
  system_prompt: |
    You are the GDPval assistant supporting the Growth, Development, and Productivity validation benchmark.
    Each task includes metadata describing the economic sector and target occupation. Reference documents are
    cached locally and exposed via helper tools. Always ground your reasoning in the provided sources and cite
    filenames when making specific claims.
  tools:
    - name: list_references
      description: Return metadata for all cached references for a GDPval task.
      parameters:
        type: object
        properties:
          task_id:
            type: string
            description: GDPval task identifier.
        required: [task_id]
    - name: read_reference
      description: Read the cached text for a specific reference file.
      parameters:
        type: object
        properties:
          task_id:
            type: string
            description: GDPval task identifier.
          filename:
            type: string
            description: Reference filename returned by list_references.
        required: [task_id, filename]
    - name: summarize_reference
      description: Summarize a reference file using the cached text.
      parameters:
        type: object
        properties:
          task_id:
            type: string
            description: GDPval task identifier.
          filename:
            type: string
            description: Reference filename returned by list_references.
          max_lines:
            type: integer
            minimum: 1
            description: Maximum number of lines to include in the summary.
        required: [task_id, filename]
  import_path: examples.gdpval.agent
  attribute: create_gdpval_agent
  working_directory: ./
  allow_generator: false
  llm:
    provider: openai
    model: gpt-5
    api_key_env: OPENAI_API_KEY
    temperature: 1.0
    timeout_seconds: 3600
    max_output_tokens: 32000
    additional_headers:
      OpenAI-Beta: reasoning=1

student:
  max_plan_tokens: 32000
  max_step_tokens: 32000
  max_synthesis_tokens: 32000
  tool_choice: auto

prompt_rewrite:
  llm:
    provider: google
    model: gemini/gemini-2.5-flash
    api_key_env: GEMINI_API_KEY
    temperature: 0.1
    timeout_seconds: 3600
    max_output_tokens: 8192
  max_tokens: 8192
  temperature: 0.1

teacher:
  llm:
    provider: openai
    model: gpt-5
    api_key_env: OPENAI_API_KEY
    temperature: 1.0
    timeout_seconds: 3600
    additional_headers:
      OpenAI-Beta: reasoning=1
  max_review_tokens: 32000
  plan_cache_seconds: 300
  guidance_max_tokens: 16000
  validation_max_tokens: 16000

orchestration:
  max_retries: 1
  step_timeout_seconds: 1200
  rim_guidance_tag: rim_feedback
  emit_intermediate_steps: true

rim:
  small_model:
    provider: google
    model: gemini/gemini-2.5-flash
    api_key_env: GEMINI_API_KEY
    max_output_tokens: 8192
  large_model:
    provider: google
    model: gemini/gemini-2.5-pro
    api_key_env: GEMINI_API_KEY
    max_output_tokens: 8192
  active_judges:
    process: true
    helpfulness: true
  variance_threshold: 0.2
  uncertainty_threshold: 0.35

storage:
  database_url: postgresql://atlas:atlas@localhost:5433/atlas
  min_connections: 1
  max_connections: 5
  statement_timeout_seconds: 30
