agent:
  type: openai
  name: supply-chain-inventory-agent
  system_prompt: |
    You are a supply chain operations analyst specializing in inventory rebalancing decisions.

    When presented with warehouse inventory scenarios, you must:
    1. Analyze warehouse utilization, demand trends, and cost factors
    2. Quantify economic trade-offs (transfer cost vs carrying cost vs stockout risk)
    3. Consider operational constraints (capacity, timing, weather, supplier lead times)
    4. Provide clear, actionable recommendations with specific calculations

    Structure your analysis:
    - Current Situation: Summarize warehouse states and demand
    - Key Factors: Identify critical decision drivers
    - Cost Analysis: Calculate transfer, carrying, and stockout costs
    - Trade-offs: Explain conflicting priorities
    - Recommendation: Clear action with quantified cost/benefit
    - Risks: Identify key uncertainties

    Always quantify your reasoning with specific numbers from the context.
  tools: []
  llm:
    provider: openai
    model: gpt-5-mini
    api_key_env: OPENAI_API_KEY
    max_output_tokens: 32000
    timeout_seconds: 600

teacher:
  llm:
    provider: openai
    model: gpt-5-mini
    api_key_env: OPENAI_API_KEY
    max_output_tokens: 32000
    timeout_seconds: 600

rim:
  small_model:
    provider: google
    model: gemini/gemini-2.5-flash
    api_key_env: GOOGLE_API_KEY
    max_output_tokens: 32000
    timeout_seconds: 600
  large_model:
    provider: google
    model: gemini/gemini-2.5-pro
    api_key_env: GOOGLE_API_KEY
    max_output_tokens: 32000
    timeout_seconds: 600
  judge_prompt: |
    Reward the agent for: (1) analyzing all critical factors (warehouse utilization, demand trends, costs, operational constraints), (2) quantifying economic impact with specific calculations, (3) providing clear actionable recommendations, (4) identifying key risks and trade-offs.
  variance_threshold: 0.15
  uncertainty_threshold: 0.3

storage:
  database_url: postgresql://atlas:atlas@localhost:5433/atlas
  min_connections: 1
  max_connections: 5
  statement_timeout_seconds: 30
